name: Node.js Run
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      file:
        description: "Choose A File To Run"
        type: choice
        options:
          - none
          - dorm_life
          - her_majesty
          - lucky
          - oops
          - power
          - return
          - shapeshifter
          - tick_tock
          - vampire
          - wakeup_call
        default: none
      verbosity:
        description: "Log Output?"
        type: boolean
        default: false
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set Log Verbosity
        id: set-verbosity
        run: |
          if [ "${{ github.event.inputs.verbosity }}" = "true" ]; then
            echo "VERBOSITY=verbose" >> $GITHUB_ENV
          else
            echo "VERBOSITY=verbose" >> $GITHUB_ENV
          fi
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - run: |
          FILE_INPUT=${{ github.event.inputs.file || '08' }}
          npm run main -- "$VERBOSITY" "$FILE_INPUT"
      - name: Configure Git
        run: |
          git config --global user.name "github-gremlin"
          git config --global user.email "github-gremlin@users.noreply.github.com"
      - name: Commit changes
        run: |
          git add .
          git commit -m "Auto-commit: update from script" || echo "No changes to commit"
          git push